{
 "title": "Application Dashboard with carbon metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Carbon metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Energy Consumed Over Time",
   "type": "timeseries",
   "description": "This panel can track the total energy consumed over time, providing insights into the overall energy efficiency of your projects.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(codecarbon_energy_consumed[$__interval])) by (project_name)",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Power Usage of Components",
   "type": "timeseries",
   "description": "This panel can show the real-time power usage of CPU, GPU, and RAM, giving you instant feedback on the power efficiency of your projects.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(rate(codecarbon_cpu_power[$__interval])) by (project_name)",
     "legendFormat": "CPU power: {{project_name}}"
    },
    {
     "expr": "avg(rate(codecarbon_gpu_power[$__interval])) by (project_name)",
     "legendFormat": "GPU power: {{project_name}}"
    },
    {
     "expr": "avg(rate(codecarbon_ram_power[$__interval])) by (project_name)",
     "legendFormat": "RAM power: {{project_name}}"
    }
   ]
  },
  {
   "title": "Emissions Rate by Project",
   "type": "barchart",
   "description": "This panel can help you compare the emissions rate (Kg/s) across different projects, identifying which projects are more carbon-efficient.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kg/s" } },
   "targets": [
    {
     "expr": "avg(codecarbon_emissions_rate) by (project_name)",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Total Emissions Over Time",
   "type": "timeseries",
   "description": "This panel can show the total CO₂-equivalents emissions over time, allowing you to monitor the environmental impact of your projects.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kg of CO₂eq" } },
   "targets": [
    {
     "expr": "sum(increase(codecarbon_emissions[$__range])) by (project_name)\n",
     "legendFormat": "{{project_name}}"
    }
   ]
  },
  {
   "title": "Energy Consumption Breakdown",
   "type": "bargauge",
   "description": "This panel can display the breakdown of energy consumption by CPU, GPU, and RAM, helping you identify which component consumes the most energy.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(codecarbon_cpu_energy[$__range])) by (project_name)",
     "legendFormat": "CPU energy: {{project_name}}"
    },
    {
     "expr": "sum(increase(codecarbon_gpu_energy[$__range])) by (project_name)",
     "legendFormat": "GPU energy: {{project_name}}"
    },
    {
     "expr": "sum(increase(codecarbon_ram_energy[$__range])) by (project_name)",
     "legendFormat": "RAM energy: {{project_name}}"
    }
   ]
  }
 ]
}