{
 "title": "Python App Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Requests Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Number of Requests per Endpoint ",
   "type": "barchart",
   "description": "The total number of requests by endpoint and status code in a bar chart to easily identify which endpoints are more active or problematic",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "{{endpoint}} : {{status}}" }
   ]
  },
  {
   "title": "Requests Created Time",
   "type": "timeseries",
   "description": "Plotting the time requests were created for each endpoint to analyze the request load and timings.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "requests_created", "legendFormat": "{{endpoint}} : {{status}}" }
   ]
  },
  {
   "title": "Requests Per Minute by Endpoint",
   "type": "timeseries",
   "description": "This query shows the number of requests per minute for each endpoint, helping to monitor the load and performance per endpoint over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(requests_total[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate by Endpoint ",
   "type": "timeseries",
   "description": "sum(rate(requests_total{status=~\"5..\"}[5m])) by (endpoint) / sum(rate(requests_total[5m])) by (endpoint)\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(requests_total{status=~\"5..\"}[5m])) by (endpoint) / sum(rate(requests_total[5m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Latency ",
   "type": "timeseries",
   "description": "This query calculates the average latency per request over a 5-minute period, grouped by endpoints. It uses a hypothetical metric request_duration_seconds_sum which should be replaced with your actual latency metric.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg(rate(requests_latency_seconds_sum[$__rate_interval])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentile Latency",
   "type": "timeseries",
   "description": "This query calculates the 95th percentile of request latency using a histogram metric request_duration_seconds_bucket. It provides insight into the upper bounds of your latency, showing how well your system performs under load.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(request_latency_seconds_bucket[$__rate_interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "Memory & Process Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Time Used ",
   "type": "stat",
   "description": "How the CPU time changes over time, useful for identifying periods of high CPU load.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"app\"}[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Growth Rate",
   "type": "timeseries",
   "description": "This derivative function calculates the rate of change in resident memory usage over time, providing insights into memory usage trends that might indicate memory leaks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "deriv(process_resident_memory_bytes{job=\"app\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Garbage Collection Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Garbage Collection Frequency by Generation ",
   "type": "timeseries",
   "description": "Frequency of garbage collections over time for each generation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    { "expr": "python_gc_collections_total\n", "legendFormat": "{{generation}}" }
   ]
  },
  {
   "title": "Total Objects Collected per Generation",
   "type": "barchart",
   "description": "The total number of objects collected by the garbage collector, separated by generation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Rate of Garbage Collection per Generation ",
   "type": "timeseries",
   "description": "This query measures the rate of change in garbage collection counts over a 5-minute interval for each generation. It's useful for observing the responsiveness of the garbage collector to changes in workload.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(python_gc_collections_total[5m])",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Average Objects Collected per Collection Event by Generation ",
   "type": "timeseries",
   "description": "This shows the average number of objects collected per collection event for each generation, which helps in understanding the efficiency of the garbage collection process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total[5m]) / rate(python_gc_collections_total[5m])",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Total Uncollectable Objects per Generation",
   "type": "barchart",
   "description": "Count of uncollectable objects, separated by generation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total",
     "legendFormat": "{{generation}}"
    }
   ]
  }
 ]
}